steps:
  - label: "🤡 :hammer:"
    plugins:
      docker-compose#v2.1.0:
        run: tests
  - label: ":sparkles: lint"
    plugins:
      plugin-linter#v1.0.0:
        name: detect-clowns
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files: hooks/**
